# Generated by Django 3.2.7 on 2021-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
