# Generated by Django 3.2.7 on 2021-09-15 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeathersFightApp', '0002_fight_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'authors'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
