# Generated by Django 3.2.7 on 2021-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0004_alter_fight_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='awaiting',
            field=models.BooleanField(default=True),
        ),
    ]
