# Generated by Django 3.2.7 on 2021-09-15 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0005_fight_awaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='await_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 14, 12, 38, 475597)),
        ),
    ]
