# Generated by Django 3.2.7 on 2021-09-15 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0007_auto_20210915_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='await_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 15, 6, 24, 913740)),
        ),
    ]
