# Generated by Django 3.2.7 on 2021-09-15 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0008_alter_fight_await_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='await_request_date',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='awaiting',
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='delete_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 20, 14, 11, 172315)),
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_request_date', models.DateTimeField(default=datetime.datetime(2021, 9, 15, 20, 14, 11, 172041))),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FeathersFightApp.fight')),
            ],
        ),
    ]
