# Generated by Django 3.2.7 on 2021-09-16 01:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeathersFightApp', '0010_auto_20210915_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='delete_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 1, 30, 39, 200805)),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='edit_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 1, 30, 39, 200526)),
        ),
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'Authors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
