# Generated by Django 3.2.7 on 2021-09-16 13:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0014_auto_20210916_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='delete_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 13, 16, 53, 241186)),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='edit_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 13, 16, 53, 240900)),
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 13, 16, 53, 240605)),
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
