# Generated by Django 3.2.7 on 2021-09-16 14:09

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0015_auto_20210916_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='delete_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 14, 9, 8, 308462)),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='edit_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 14, 9, 8, 308122)),
        ),
        migrations.AlterField(
            model_name='fight',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 14, 9, 8, 307797)),
        ),
    ]
