# Generated by Django 3.2.7 on 2021-09-17 19:39

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeathersFightApp', '0022_auto_20210916_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='delete_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 39, 54, 738592)),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='edit_request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 39, 54, 737847)),
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 39, 54, 737241)),
        ),
        migrations.CreateModel(
            name='SavePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
                ('last_save', models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 39, 54, 737553))),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'Authors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
