# Generated by Django 3.2.7 on 2021-09-18 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0023_auto_20210917_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='publication',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='style',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 18, 19, 14, 658028)),
        ),
        migrations.AlterField(
            model_name='savepublication',
            name='last_save',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 18, 19, 14, 658356)),
        ),
        migrations.DeleteModel(
            name='DeleteRequest',
        ),
        migrations.DeleteModel(
            name='EditRequest',
        ),
    ]
