# Generated by Django 3.2.7 on 2021-09-19 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeathersFightApp', '0026_auto_20210919_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationrequest',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 0, 54, 49, 970185)),
        ),
        migrations.AlterField(
            model_name='savepublication',
            name='last_save',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 0, 54, 49, 970523)),
        ),
    ]
