# Generated by Django 3.2.7 on 2021-09-19 18:41

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeathersFightApp', '0027_auto_20210919_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
                ('request_datetime', models.DateTimeField(default=datetime.datetime(2021, 9, 19, 18, 41, 42, 929056))),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'Authors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
                ('last_save', models.DateTimeField(default=datetime.datetime(2021, 9, 19, 18, 41, 42, 929485))),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'Authors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Fight',
            new_name='Article',
        ),
        migrations.RemoveField(
            model_name='savepublication',
            name='author',
        ),
        migrations.DeleteModel(
            name='PublicationRequest',
        ),
        migrations.DeleteModel(
            name='SavePublication',
        ),
    ]
